version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/pino"
    versions:
    - 6.3.5
    - 6.3.6
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
    - 0.30.0
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
    - 3.9.9
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: tslint-immutable
    versions:
    - 6.0.1
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@types/bluebird"
    versions:
    - 3.5.33
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: rimraf
    versions:
    - 3.0.2
  - dependency-name: typed-emitter
    versions:
    - 1.3.1
  - dependency-name: "@types/uuid"
    versions:
    - 8.3.0
  - dependency-name: dotenv-cli
    versions:
    - 4.0.0
  registries:
  - npm-registry-registry-npmjs-org
